name: Gradle_BUILD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Gradle_Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    
    - name: TEST
      run: |
          ls -la
          ls -la ./my-spring-board/gradlew


    - name: Grant execute permission for gradlew
      run: chmod +x ./my-spring-board/gradlew/gradlew

    - name: Build with Gradle
      run: ./my-spring-board/gradlew build
