name: WAR_Build && Docker_Image

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job-01:
    name: Gradle_Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew


    - name: Build with Gradle
      run: ./gradlew build

    - name: TEST
      run: ls -la


    - name: Upload war file to artifact
      uses: actions/upload-artifact@v2
      with:
        name: WAR with Gradle
        path: ./build/libs/*.war

        
    - name: TEST
      run: ls -Rla


    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ywd-devops:latest


    - name: TEST
      run: ls -R