name: Gradle_BUILD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job-01:
    name: Gradle_Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    
    
    - name: TEST
      run: |
          ls -la
          ls -la ./my-spring-board/gradlew

#  job-02:
#    needs: job-01
#    name: Artifact_Setup


    - name: Grant execute permission for gradlew
      run: chmod +x ./my-spring-board/gradlew

    - name: Build with Gradle
      run: ./my-spring-board/gradlew build


    - name: Upload war file to artifact
      uses: actions/upload-artifact@v2
      with:
        name: war-package
        path: ./build/libs/*.war

    - name: Upload war file to artifact
      uses: actions/upload-artifact@v2
      with:
        name: war-package
        path: ./my-spring-board/build/libs/*.war