name: GCE Connect And Execute Script


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          service-account-key: ${{ secrets.GCP_SA_KEY }} # base64-encoded service account JSON key
          confgure-docker: true

      - name: GCP Github Action
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}
      

