name: GKE-TEST


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: was 
  IMAGE: cocopopo/ywd-devops:latest


jobs:
  Setup_GCP-GKE:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: GCP Github Action
        uses: google-github-actions/setup-gcloud@master
        with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

      - id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: cluster-1
          location: us-central1-c
          credentials: ${{ secrets.GCP_SA_KEY }}


      - name: Deploy-Update
        run: kubectl rollout status deployment/$DEPLOYMENT_NAME 

      - name: get-all
        run: kubectl get all
