name: Gradle_TEST

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job-01:
    name: Gradle_Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
